<a href="https://colab.research.google.com/github/ChicIceCream/Jupyter-Notebooks/blob/master/Learning_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf


In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)


tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_one_d = tf.constant([2,0,-3,80,9])
print(tensor_one_d)

tf.Tensor([ 2  0 -3 80  9], shape=(5,), dtype=int32)


In [10]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,45,-1],
    [2,3,4],
    ])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3 45 -1]
 [ 2  3  4]], shape=(3, 3), dtype=int32)
